### ISSUE TITLE
我有一个项目和这个项目类似！有想更新它的想法！

### ISSUE THREAD

**Issue by ghost** [MagicGroup/eva#1]
哈哈

**Comment by liudidi** [comment]
你的意思是更新eva还是你的项目？eva原来开发的时候是黑箱分析协议的，很麻烦，不知道你的goQQ是怎么样的。网络这方面的开发我基本不懂。如果你有意更新此项目，我十分欢迎。不过eva本身是kde3的，目前我是把它转到的tde上，理想的状况是转到qt4上，本来有一个qt4版本，不过我找不到了。

**Comment by ghost** [comment]
我已经 用过黑箱分析过协议了！我的goqq已经能够 登录！但是由于go语言的限制（主要是没有一个像样的gui），所以我打算重新用C写！我不打算使用原eva的代码。

**Comment by liudidi** [comment]
用C?不是有个gtkqq啊。

**Comment by ghost** [comment]
那个是webqq的协议！

**Comment by liudidi** [comment]
噢，你完全重写？gui方面用什么呢？

**Comment by SunRain** [comment]
goQQ已经能够正常登入和聊天了吗？不是很懂这方面的东西，不过界面是否可以参考kde的版本呢？现在的webqq虽然不错，但是用网页的方式始终感觉不是很舒服

**Comment by ekd123** [comment]
@lifulinghan 乃发个消息吊个胃口就又不见了。。。快更快更！

**Comment by ghost** [comment]
@ekd123 乃没看到我的项目里有一个libeva了吗？TOM都准备为这东西写GTK界面！乃就为它写QT界面吧！我都是挤时间来写的，我还要找工作~~~~~~

**Comment by ekd123** [comment]
@lifulinghan 乃认为我会写Qt界面么？~~~至少是 Mx 吧！

**Comment by ghost** [comment]
@ekd123 我们都 认为乃是万能的！
